# 十、错误处理

在本章中，我们将介绍错误、异常以及如何查找和修复它们。处理异常是编写可靠和可用代码的重要部分。我们将介绍基本的内置异常，并展示如何使用和处理异常。我们将介绍调试，并向您展示如何使用内置的 Python 调试器。

# 有哪些例外？

程序员(即使是有经验的程序员)发现的一个错误是代码有不正确的语法，这意味着代码指令的格式不正确。

考虑一个语法错误的例子:

```py
>>> for i in range(10)
  File “<stdin>”, line 1
    for i in range(10)
                      ^
SyntaxError: invalid syntax
```

出现错误是因为`for`声明末尾缺少冒号。这是引发异常的一个示例。在`SyntaxError`的情况下，它告诉程序员代码有不正确的语法，并打印错误发生的行，箭头指向该行中的问题所在。

Python 中的异常是从名为`Exception`的基类派生(继承)而来的。Python 有许多内置的例外。一些常见的异常类型列于*表 10.1、*(内置异常的完整列表参见*[【38】](16.html "Appendix . References")*)。

以下是两个常见的例外示例。如你所料，当你试图除以 0 时`ZeroDivisionError`被提升。

```py
def f(x):
    return 1/x

>>> f(2.5)
0.4 
>>> f(0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "exception_tests.py", line 3, in f
    return 1/x
ZeroDivisionError: integer division or modulo by zero
```

<colgroup><col> <col></colgroup> 
| 例外 | **描述** |
| `IndexError` | 索引越界，例如，当 v 只有 5 个元素时，`v[10]` |
| `KeyError` | 对未定义的字典键的引用 |
| `NameError` | 找不到名称，例如未定义的变量 |
| `LinAlgError` | `linalg`模块中的错误，例如，当用奇异矩阵求解系统时 |
| `ValueError` | 不兼容的数据值，例如，当使用不兼容数组的`dot`时 |
| `IOError` | 输入/输出操作失败，例如，“找不到文件” |
| `ImportError` | 导入时找不到模块或名称 |

表 10.1:一些常用的内置异常及其含义

零除会引发`ZeroDivisionError`并打印出发生错误的文件、行和函数名。

正如我们之前看到的，数组只能包含相同数据类型的元素。如果您试图分配一个不兼容类型的值，则会引发`ValueError`。值错误的示例:

```py
>>> a = arange(8.0) 
>>> a 
array([ 0., 1., 2., 3., 4., 5., 6., 7.]) 
>>> a[3] = 'string'
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: string
```

这里，引发`ValueError`是因为数组包含浮点，并且不能为元素分配字符串值。

## 基本原则

让我们看看如何使用异常的基本原则，用`raise`引发异常，用`try`语句捕捉异常。

### 引发异常

创建错误被称为引发异常。在前一节中，您看到了一些异常示例。您也可以定义自己的预定义类型或无类型的例外。使用如下命令可以引发异常:

```py
raise Exception("Something went wrong")
```

当出现问题时，很容易打印出错误消息，例如:

```py
print("The algorithm did not converge.")
```

出于多种原因，不建议这样做。首先，打印输出很容易被遗漏，尤其是当信息被隐藏在打印到控制台的许多其他信息中时。其次，更重要的是，它会使您的代码无法被其他代码使用。调用代码将无法知道发生了错误，因此无法处理它。

由于这些原因，最好还是引发异常。异常应始终包含描述性消息，例如:

```py
raise Exception("The algorithm did not converge.")
```

这条信息对用户来说会很明显。它还为调用代码提供了知道发生了错误并可能找到补救方法的机会。

下面是一个典型的例子，检查函数内部的输入，以确保它在继续之前是可用的。例如，对负值和正确数据类型的简单检查确保了计算阶乘的函数的预期输入:

```py
def factorial(n):
  if not (n >=0 and isinstance(n,(int,int32,int64))):
    raise ValueError("A positive integer is expected")
    ...
```

如果给出了不正确的输入，函数的用户将立即知道错误是什么，处理异常是用户的责任。请注意在引发预定义异常类型时异常名称的使用，在这种情况下`ValueError`后跟消息。通过指定异常的类型，调用代码可以根据引发的错误类型决定以不同的方式处理错误。

总而言之，引发异常总是比打印错误消息更好。

### 捕捉异常

处理异常被称为捕获异常。使用`try`和`except`命令检查异常。

异常会停止程序执行流程，并寻找最近的`try`封闭块。如果没有捕获到异常，程序单元被留下，它继续在调用栈中较高的程序单元中搜索下一个封闭的`try`块。如果没有找到任何块，并且没有处理异常，则执行完全停止；将显示标准追溯信息。

让我们看一个`try`语句的例子:

```py
try:
    <some code that might raise an exception>
except ValueError:
    print("Oops, a ValueError occurred")
```

在这种情况下，如果`try`块中的代码引发了类型为`ValueError`的错误，将会捕获异常并打印`except`块中的消息。如果在`try`块内没有发生异常，`except`块被完全跳过，继续执行。

`except`语句可以捕捉多个异常。这是通过简单地将它们分组到一个元组中来完成的，如下所示:

```py
except (RuntimeError, ValueError, IOError):
```

`try`块也可以有多个`except`语句。这使得根据类型以不同的方式处理异常成为可能。让我们看一个多种异常类型的例子:

```py
try:
    f = open('data.txt', 'r')
    data = f.readline()
    value = float(data)
except OSError as oe:
    print("{}:  {}".format(oe.strerror, oe.filename))
except ValueError:
    print("Could not convert data to float.")
```

例如，如果文件不存在，这里将捕捉到一个`OSError`；例如，如果文件第一行中的数据与浮点数据类型不兼容，则会捕获一个`ValueError`。

在本例中，我们通过关键字`as`将`OSError`分配给变量`oe`。这允许在处理该异常时访问更多细节。这里我们打印了错误字符串`oe.strerror`和相关文件的名称`oe.filename`。根据类型的不同，每种错误类型都可以有自己的一组变量。如果文件不存在，在前面的示例中，消息将是:

```py
I/O error(2): No such file or directory
```

另一方面，如果文件存在，但您没有打开它的权限，消息将是:

```py
I/O error(13): Permission denied
```

这是捕获异常时格式化输出的有用方法。

`try` - `except`组合可以通过可选的`else`和`finally`模块进行扩展。使用`else`的例子可以在[第 13 章](13.html "Chapter 13. Testing")*测试*的*测试等分算法*部分看到。当最终需要进行清理工作时，将`try`和`finally`结合起来会给出一个有用的结构:

确保文件正确关闭的示例:

```py
try:
    f = open('data.txt', 'r')
    # some function that does something with the file
    process_file_data(f) 
except: 
    ... 
finally:
    f.close()
```

这将确保无论在处理文件数据时引发什么异常，文件最终都是关闭的。在`try`语句中没有处理的异常在`finally`块之后被保存和引发。这个组合用在`with`语句中；请参见*上下文管理器-附带声明*一节。

## 用户定义的异常

除了内置的 Python 异常，还可以定义自己的异常。这种用户定义的异常应该继承自`Exception`基类。当您定义自己的类时，如第 14 章*综合示例*的*多项式*一节中的多项式类，这可能会很有用。

看看这个简单的用户定义异常的小例子:

```py
class MyError(Exception):
    def __init__(self, expr):
        self.expr = expr
    def __str__(self):
        return str(self.expr)

try:
   x = random.rand()
   if x < 0.5:
      raise MyError(x)
except MyError as e:
   print("Random number too small", e.expr)
else:
   print(x)
```

生成一个随机数。如果该数字低于 0.5，将引发异常，并打印一条消息，指出该值太小。如果没有引发异常，则打印该数字。

在本例中，您还看到了在`try`语句中使用`else`的情况。如果没有异常发生，`else`下的区块将被执行。

建议您使用以`Error`结尾的名称定义异常，如标准内置异常的命名。

## 上下文管理器 with 语句

Python 中有一个非常有用的构造，用于在处理上下文(如文件或数据库)时简化异常处理。该语句将`try ... finally`结构封装在一个简单的命令中。下面是一个使用`with`读取文件的例子:

```py
with open('data.txt', 'r') as f:
    process_file_data(f)
```

这将尝试打开文件，对文件运行指定的操作(例如，读取)，并关闭文件。如果在执行`process_file_data`的过程中出现任何问题，文件会被正确关闭，然后引发异常。这相当于:

```py
f = open('data.txt', 'r')
try: 
    # some function that does something with the file 
    process_file_data(f) 
except:
    ... 
finally:
    f.close()
```

我们将在[第 12 章](12.html "Chapter 12. Input and Output")、*输入输出*的*文件处理*一节中，在读写文件时使用这个选项。

前面的文件读取示例是使用上下文管理器的示例。上下文管理器是 Python 对象，有两种特殊的方法，`_ _enter_ _`和`_ _exit_ _`。实现这两种方法的类的任何对象都可以用作上下文管理器。在这个例子中，文件对象`f`是一个上下文管理器，因为有`f._ _enter_ _`和`f._ _exit_ _`方法。

`_ _enter_ _`方法应该实现初始化指令，比如打开文件或者数据库连接。如果此方法有一个返回语句，则使用`as`构造访问返回的对象。否则省略`as`关键字。`_ _exit_ _`方法包含清理指令，例如，关闭文件或提交事务并关闭数据库连接。如需了解更多解释和自写上下文管理器示例，请参阅第 13 章、*测试*的*使用上下文管理器计时*一节。

有一些 NumPy 函数可以用作上下文管理器。例如`load`功能支持某些文件格式的上下文管理器。NumPy 的函数`errstate`可以用作上下文管理器，指定代码块内的浮点错误处理行为。

下面是使用 errstate 和上下文管理器的一个示例:

```py
import numpy as np      # note, sqrt in NumPy and SciPy 
                        # behave differently in that example
with errstate(invalid='ignore'):
    print(np.sqrt(-1)) # prints 'nan'

with errstate(invalid='warn'):
    print(np.sqrt(-1)) # prints 'nan' and 
                   # 'RuntimeWarning: invalid value encountered in sqrt'

with errstate(invalid='raise'):
    print(np.sqrt(-1)) # prints nothing and raises FloatingPointError
```

参考[第 2 章](02.html "Chapter 2. Variables and Basic Types")、*变量和基本类型*的*无限和非数字*部分，了解本例的更多细节，参考[第 13 章](13.html "Chapter 13. Testing")、*测试*的*部分，了解另一个示例。*

# 查找错误:调试

软件代码中的错误有时被称为*bug*。调试是发现和修复代码中的错误的过程。这个过程可以在不同的复杂程度下进行。最有效的方法是使用一种叫做调试器的工具。进行单元测试是早期识别错误的好方法，请参考第 13 章、*测试*的*使用单元测试*一节。当不清楚问题在哪里或者是什么的时候，调试器是非常有用的。

## 虫子

通常有两种错误:

*   会引发异常，但不会被捕获。
*   代码运行不正常。

第一种情况通常更容易解决。第二个可能更难，因为问题可能是一个错误的想法或解决方案，一个错误的实现，或者两者的结合。

我们只关心接下来的第一种情况，但是同样的工具可以用来帮助找到为什么代码没有做它应该做的事情。

## 堆栈

当引发异常时，您会看到调用堆栈。调用堆栈包含调用引发异常的代码的所有函数的跟踪。

一个简单的堆栈示例:

```py
def f():
   g()
def g():
   h()
def h():
   1//0

f()
```

这种情况下的堆栈是`f`、 `g`和`h`。运行这段代码生成的输出如下所示:

```py
Traceback (most recent call last):
  File "stack_example.py", line 11, in <module>
    f() 
  File "stack_example.py", line 3, in f
    g() 
  File "stack_example.py", line 6, in g
    h() File "stack_example.py", line 9, in h
    1//0 
ZeroDivisionError: integer division or modulo by zero
```

打印错误。显示了导致错误的函数序列。第 11 行的函数`f`被调用，依次调用`g`和`h`。这就造成了`ZeroDivisionError`。

堆栈跟踪报告程序执行中某一点的活动堆栈。堆栈跟踪允许您跟踪调用到给定点的函数序列。通常这是在引发了未捕获的异常之后。这有时被称为事后分析，堆栈跟踪点就是异常发生的地方。另一种选择是手动调用堆栈跟踪来分析您怀疑有错误的代码段，可能是在异常发生之前。

## Python 调试器

Python 自带一个名为 pdb 的内置调试器。一些开发环境集成了调试器。以下过程在大多数情况下仍然适用。

使用调试器最简单的方法是在您想要调查的代码点启用堆栈跟踪。下面是基于[第七章](07.html "Chapter 7. Functions")、*函数*的*返回值*一节中提到的例子触发调试器的一个简单例子:

```py
import pdb

def complex_to_polar(z):
    pdb.set_trace() 
    r = sqrt(z.real ** 2 + z.imag ** 2)
    phi = arctan2(z.imag, z.real)
    return (r,phi)
z = 3 + 5j 
r,phi = complex_to_polar(z)

print(r,phi)
```

`pdb.set_trace()`命令启动调试器并启用后续命令的跟踪。前面的代码将显示这一点:

```py
> debugging_example.py(7)complex_to_polar()
-> r = sqrt(z.real ** 2 + z.imag ** 2) 
(Pdb)
```

调试器提示用(Pdb)表示。调试器停止程序执行，并给你一个提示，让你检查变量，修改变量，单步执行命令，等等。

每一步都会打印当前行，因此您可以跟踪自己的位置以及接下来会发生什么。通过命令`n`(下一步)来执行命令，如下所示:

```py
> debugging_example.py(7)complex_to_polar() 
-> r = sqrt(z.real ** 2 + z.imag ** 2) 
(Pdb) n 
> debugging_example.py(8)complex_to_polar() 
-> phi = arctan2(z.imag, z.real) 
(Pdb) n 
> debugging_example.py(9)complex_to_polar() 
-> return (r,phi) 
(Pdb) 
...
```

命令`n`(下一步)将继续到下一行并打印该行。如果需要同时查看多行，列表命令`l`(列表)显示当前行及周围代码:

在调试器中列出周围的代码:

```py
> debugging_example.py(7)complex_to_polar() 
-> r = sqrt(z.real ** 2 + z.imag ** 2) 
(Pdb) l
  2
  3 import pdb
  4
  5 def complex_to_polar(z):
  6 pdb.set_trace()
  7 -> r = sqrt(z.real ** 2 + z.imag ** 2)
  8 phi = arctan2(z.imag, z.real)
  9 return (r,phi)
 10
 11 z = 3 + 5j
 12 r,phi = complex_to_polar(z) 
(Pdb)
```

变量的检查可以通过使用命令`p`(打印)后跟变量名将其值打印到控制台来完成。打印变量的示例:

```py
> debugging_example.py(7)complex_to_polar() 
-> r = sqrt(z.real ** 2 + z.imag ** 2) 
(Pdb) p z 
(3+5j) (Pdb) n 
> debugging_example.py(8)complex_to_polar() 
-> phi = arctan2(z.imag, z.real) 
(Pdb) p r 
5.8309518948453007 
(Pdb) c 
(5.8309518948453007, 1.0303768265243125)
```

`p`(打印)命令将打印变量；命令`c`(继续)继续执行。

在执行过程中更改变量是有用的。只需在调试器提示符下分配新值，然后单步执行或继续执行。

一个改变变量的例子:

```py
> debugging_example.py(7)complex_to_polar() 
-> r = sqrt(z.real ** 2 + z.imag ** 2) 
(Pdb) z = 2j 
(Pdb) z 
2j 
(Pdb) c 
(2.0, 1.5707963267948966)
```

这里，变量`z`被赋予一个新值，在剩余代码中使用。请注意，最终打印结果已经更改。

## 概述-调试命令

在*表 10.2* 中，显示了最常见的调试命令。有关命令的完整列表和描述，请参见文档[【25】](16.html "Appendix . References")了解更多信息。请注意，任何 Python 命令也可以工作，例如，为变量赋值。

### 型式

**短变量名**

如果要检查名称与调试器的任何短命令一致的变量，例如`h`，必须使用`!h`显示该变量。

<colgroup><col> <col></colgroup> 
| **命令** | **动作** |
| `h` | 帮助(没有参数，它打印可用的命令) |
| `l` | 列出当前行周围的代码 |
| `q` | 退出(退出调试器，执行停止) |
| `c` | 继续执行 |
| `r` | 继续执行，直到当前函数返回 |
| `n` | 继续执行，直到下一行 |
| `p <expression>` | 计算并打印当前上下文中的表达式 |

表 10.2:调试器最常见的调试命令。

## IPython 中的调试

IPython 附带了名为`ipdb`的调试器版本。在撰写本书时，差异非常小，但这可能会改变。

IPython 中有一个命令，在出现异常时自动打开调试器。这在尝试新想法或代码时非常有用。如何在 IPython 中自动打开调试器的示例:

```py
In [1]: %pdb # this is a so - called IPython magic command 
Automatic pdb calling has been turned ON

In [2]: a = 10

In [3]: b = 0

In [4]: c = a/b
___________________________________________________________________
ZeroDivisionError                  Traceback (most recent call last) 
<ipython-input-4-72278c42f391> in <module>() 
—-> 1 c = a/b

ZeroDivisionError: integer division or modulo by zero 
> <ipython-input-4-72278c42f391>(1)<module>()
      -1 c = a/b
ipdb>
```

IPython 提示符下的 IPython 魔法命令`%pdb`在引发异常时自动启用调试器。这里调试器提示显示`ipdb`来指示调试器正在运行。

# 总结

本章中的关键概念是异常和错误。我们展示了一个异常是如何在另一个程序单元中被捕获的。您可以定义自己的异常，并为它们配备消息和给定变量的当前值。

代码可能会返回意外结果，但不会引发异常。定位错误结果来源的技术称为调试。我们介绍了调试方法，并希望鼓励您对它们进行培训，以便在需要时随时可用。认真调试的需求来得比你预期的要早。